name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install coverage
      run: pip install pytest-cov


    - name: Download model files
      run: |
        mkdir -p models
        wget <CustomerChurn_Prediction/models> -O models/preprocessor.pkl
        wget <CustomerChurn_Prediction/models> -O models/random_forest_churn_from_script.pkl
        wget <CustomerChurn_Prediction/models> -O models/model_columns.pkl

    - name: Run tests with coverage
      run: |
        PYTHONPATH=. pytest --cov=src --cov=app --cov-report=term

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image (amd64)
      run: |
        docker buildx build --platform linux/amd64 \
          -t manojram7/customer-churn-api:${{ github.sha }} \
          --push .

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container App
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az containerapp update \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image manojram7/customer-churn-api:${{ github.sha }}