name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install coverage
      run: pip install pytest-cov

    - name: Run tests with coverage
      run: |
        PYTHONPATH=. pytest --cov=src --cov=app --cov-report=term tests/

    - name: Build Docker image
      run: docker build -t customer-churn-api:${{ github.sha }} .

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Tag Docker image
      run: docker tag customer-churn-api:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/customer-churn-api:${{ github.sha }}

    - name: Push Docker image
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer-churn-api:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/customer-churn-api:${{ github.sha }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}









"""

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install coverage
      run: pip install pytest-cov

    - name: Run tests with coverage
      run: |
        PYTHONPATH=. pytest --cov=src --cov=app --cov-report=term tests

        """